### ISSUE TITLE
Melon shooter crashes the server

### ISSUE THREAD

**Issue by KelvinZhang512** [AzulConspirator/AzulConspirator-Create-ContraptionCreatures#6]
I shot a melon towards a skeleton and the server crashes, the reports and console logs are as following.
[latest.log](https://github.com/user-attachments/files/15515720/latest.log)
[crash-2024-05-31_23.19.46-server.txt](https://github.com/user-attachments/files/15515722/crash-2024-05-31_23.19.46-server.txt)

**Comment by AzulConspirator** [comment]
its a particle issue. should be fixed by the next patch

**Comment by KelvinZhang512** [comment]
It's still not fixed?
[crash-2024-12-26_22.30.44-server.txt](https://github.com/user-attachments/files/18253418/crash-2024-12-26_22.30.44-server.txt)

**Comment by FlushedRay** [comment]
@AzulConspirator can you just remove them if it's going to cause a crash and you don't care enough to fix it? I don't want more people bricking their servers.
